### ISSUE TITLE
How can I disablle user click action while scrolling

### ISSUE THREAD

**Issue by Srj-Love** [aliahmedbd/Ticker-Using-Recycler-View-Android#7]
I tried your code and it's working fine, but I have some issue.

When user touch on that Recyclerview the scrolling stops automatically, I tried to disable Recyclerview click  but not worked, 

Please give a solution, how can I not interrupt scrolling animation while user actions.

Thank you.

**Comment by aliahmedbd** [comment]
Hi Srj-Love,

There is an OnClickListener in AutoScrollActivity, which is:
 scrollStockAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                Toast.makeText(AutoScrollActivity.this, "Item clicked", Toast.LENGTH_LONG).show();
            }
        });
Just erase this click listener for disabling user click action
